#!/usr/bin/env python3
"""
TonicPhysio Technical SEO Audit v2.0 — Enigma Unified
Single-file audit: sitemap → crawl → report
"""
import requests, sys, json
from bs4 import BeautifulSoup
from datetime import datetime
from pathlib import Path

HEADERS = {"User-Agent": "Mozilla/5.0 (compatible; OpenClawBot/1.0)"}
TIMEOUT = 15
REPORTS_DIR = Path("/Users/sheikhown/.openclaw/workspace/reports")


def fetch(url: str) -> BeautifulSoup | None:
    try:
        r = requests.get(url, headers=HEADERS, timeout=TIMEOUT)
        r.raise_for_status()
        return BeautifulSoup(r.text, "html.parser")
    except Exception as e:
        print(f"  ⚠️  {url}: {e}")
        return None


def audit_page(url: str) -> dict:
    soup = fetch(url)
    if not soup:
        return {"url": url, "ok": False, "error": "fetch failed"}

    # strip nav/footer/script/style
    for tag in soup.find_all(["nav", "footer", "script", "style"]):
        tag.decompose()

    title = soup.title.string.strip() if soup.title else ""
    meta = soup.find("meta", attrs={"name": "description"})
    meta_desc = meta.get("content", "").strip() if meta else ""
    h1s = [h.get_text(strip=True) for h in soup.find_all("h1")]
    h2s = soup.find_all("h2")
    body = soup.find("body")
    words = len(body.get_text(separator=" ", strip=True).split()) if body else 0
    internal = sum(
        1
        for a in soup.find_all("a", href=True)
        if "tonicphysio.com" in a["href"] or a["href"].startswith("/")
    )
    canonical = bool(soup.find("link", rel="canonical"))
    schema = bool(
        soup.find("script", type="application/ld+json", string=re.compile("LocalBusiness|MedicalClinic|Physician"))
    )

    issues = []
    if len(h1s) != 1:
        issues.append(f"H1={len(h1s)}")
    if words < 800:
        issues.append(f"thin({words})")
    if not meta_desc:
        issues.append("no-meta")
    elif len(meta_desc) > 160:
        issues.append(f"meta-long({len(meta_desc)})")
    if not canonical:
        issues.append("no-canonical")
    if not schema:
        issues.append("no-schema")
    if internal < 3:
        issues.append(f"links({internal})")

    return {
        "url": url,
        "ok": True,
        "title_len": len(title),
        "meta_len": len(meta_desc),
        "h1_count": len(h1s),
        "h2_count": len(h2s),
        "words": words,
        "internal_links": internal,
        "canonical": canonical,
        "schema": schema,
        "issues": issues,
    }


def get_sitemap(url: str = "https://tonicphysio.com/page-sitemap.xml") -> list[str]:
    soup = fetch(url)
    if not soup:
        return []
    return [loc.text for loc in soup.find_all("loc")]


def generate_markdown(results: list[dict]) -> str:
    lines = [
        "# TonicPhysio Technical SEO Audit",
        f"**Date:** {datetime.now().strftime('%Y-%m-%d %H:%M')}",
        f"**Pages:** {len(results)}",
        "",
        "## Quick Summary",
        "",
        "| Page | Title | Meta | H1 | H2 | Words | Links | Schema | Canonical | Issues |",
        "|------|-------|------|----|----|-------|-------|--------|-----------|--------|",
    ]
    for r in results:
        if not r["ok"]:
            continue
        short = r["url"].replace("https://tonicphysio.com", "")
        lines.append(
            f"| {short[:40]} | {r['title_len']} | {r['meta_len']} | {r['h1_count']} | {r['h2_count']} | {r['words']} | {r['internal_links']} | {'✅' if r['schema'] else '❌'} | {'✅' if r['canonical'] else '❌'} | {', '.join(r['issues']) or '—'} |"
        )

    # grouped issues
    lines += ["", "## Issues by Category", ""]
    categories = {
        "Missing H1": [r for r in results if r["ok"] and r["h1_count"] == 0],
        "Multiple H1s": [r for r in results if r["ok"] and r["h1_count"] > 1],
        "Thin Content (<800 words)": [r for r in results if r["ok"] and r["words"] < 800],
        "Missing Meta": [r for r in results if r["ok"] and r["meta_len"] == 0],
        "Meta Too Long (>160)": [r for r in results if r["ok"] and r["meta_len"] > 160],
        "No Schema": [r for r in results if r["ok"] and not r["schema"]],
        "No Canonical": [r for r in results if r["ok"] and not r["canonical"]],
        "Low Internal Links (<3)": [r for r in results if r["ok"] and r["internal_links"] < 3],
    }
    for label, pages in categories.items():
        if pages:
            lines.append(f"### {label} ({len(pages)})")
            for r in pages:
                lines.append(f"- {r['url'].replace('https://tonicphysio.com', '')}")
            lines.append("")

    lines += ["", "---", "*Generated by Enigma*"]
    return "\n".join(lines)


def main():
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    urls = get_sitemap()
    if not urls:
        print("❌ No URLs found in sitemap")
        sys.exit(1)

    # filter service pages
    kws = ["/physiotherapy", "/massage", "/osteopathy", "/shockwave", "/acupuncture", "/orthotics"]
    urls = [u for u in urls if any(k in u for k in kws) and "/guide/" not in u and "/blog/" not in u]

    print(f"🦞 Auditing {len(urls)} pages...")
    results = [audit_page(u) for u in urls]

    md = generate_markdown(results)
    out = REPORTS_DIR / f"tonicphysio-audit-{datetime.now().strftime('%Y%m%d')}.md"
    out.write_text(md)
    print(f"\n✅ Report saved: {out}")

    ok = sum(1 for r in results if r["ok"] and not r["issues"])
    print(f"   Pages passing all checks: {ok}/{len(results)}")


if __name__ == "__main__":
    main()
