<?php
/**
 * Scraped ccell product copy. Images are media-pack keys only.
 *
 * @package Justccell
 */
declare(strict_types=1);
if (!defined('ABSPATH')) {
    exit;
}

/**
 * @return array<string, array<string, mixed>>
 */
function justccell_product_pages_data(): array
{
    return [
        'tank' => [
            'name'     => 'Tank',
            'category' => 'all-in-ones',
            'tagline'  => 'Compact Size, Large Oil Capacity, Complete Oil Compatibility',
            'subtitle' => 'Large Oil Capacity All-In-One Vaporizer',
            'banner'   => 'public_uploads_images_20240812_92d893bc1556b73225bdd65a97795d5b.jpg',
            'gallery'  =>             [
                'public_uploads_images_20240507_622e6cebbbb7055185e806fd2b593268.png',
                'public_uploads_images_20240507_036cfe495c3b090387a77086a1b8dca3.png',
                'public_uploads_images_20240812_ecd6251ca0c25e0cc0670e258a1105b6.png',
                'public_uploads_images_20240812_5c0ed5cfa8be11eaf1973ca747aebee7.png',
                'public_uploads_images_20240812_c8aacaa36440a355b98d9b4e6e3b9d55.png',
                'public_uploads_images_20240812_4b77ce35f4f058ad21387cfc324a2fa5.png',
                'public_uploads_images_20240812_26d00c337b9b28df435ff6fc6a8abde0.png',
                'public_uploads_images_20240812_63f2fb1ddeacbb6cfc2b46c8c522c205.png',
                'public_uploads_images_20240812_1f1d5c5a7ea7a4179bdf04f67fbeb47e.png',
            ],
            'spin'     => justccell_product_spin_keys('tank-360', 36),
            'specs'    =>             [
                'Tank volume: 1ml/2ml/3ml',
                'Battery capacity: 200mAh/280mAh',
                '1ml Dimensions: 71.94H x 41.35W x 16.98D (mm)/2.83H x 1.63W x 0.67D (in)',
                '2ml/3ml Dimensions: 72.2H x 41.4W x 17D (mm)/2.84H x 1.63W x 0.67D (in)',
                'Compatible with all types of cannabis oils',
                '3 re-programmable voltage settings (2.4/2.8/3.2V)',
                '10-second preheat',
                'Child-resistant lock',
                'Aroma seal-off and anti-leakage switch (optional)',
                'Clog-free dual air vents',
                'Clean vapor and enhanced safety via isolated airway',
                'Inhale activated',
                'USB-C charging',
                'Available for customization',
            ],
            'features' => [
                [
                    'title' => 'Miniature Design, Extended Experience',
                    'copy'  => 'Small enough to easily conceal in the palm of your hand, the Tank keeps consumption as discreet as possible. That said, the oil tank built within is capable of 1ml/2ml/3ml oil capacities, ensuring lasting on-the-go experiences every time.',
                    'note'  => '',
                    'image' => 'public_uploads_images_20240506_e60d5915f1ab555868ebc36d50a41b6b.jpg',
                ],
                [
                    'title' => 'Complete Oil Compatibility',
                    'copy'  => 'Designed to be compatible with all cannabis oils (distillate, live resin, live rosin, liquid diamonds, etc.), the Tank brings out the best from your extracts and provides your customers with true-to-strain, clog-free, cloud-filled enjoyment.',
                    'note'  => '',
                    'image' => 'public_uploads_images_20240506_a498121b67ccdd5c826b3c74bbcb34c9.jpg',
                ],
                [
                    'title' => 'No More Leaks or Loud Pockets',
                    'copy'  => 'The Tank’s magic switch',
                    'note'  => '',
                    'image' => 'public_uploads_images_20240506_91f67d4501c135393bf11dd9086d28c9.jpg',
                ],
                [
                    'title' => '3 Reprogrammable Voltage Settings',
                    'copy'  => 'The Tank gives your customers the option to choose between 3 preset voltage settings (2.4V, 2.8V, 3.2V) for truly customizable levels of flavor and vapor. You can also reprogram these voltages to 3 different selections from 9 available options ranging from 2.0V-3.6V via the Justccell Voltage Tuner* to match the device precisely to the oil you are filling it with. *Justccell Voltage Tuner sold separately',
                    'note'  => '',
                    'image' => 'public_uploads_images_20240506_8e00a1242167b6a9fee197a33134980b.jpg',
                ],
                [
                    'title' => 'Hassle-Free Batch-Capping',
                    'copy'  => 'Streamline your production process with a quick, hassle-free snap, and save valuable time and resources with our snap-fit mouthpiece design. Batch-capped at 15 pieces',
                    'note'  => '*Maximum batch-capping quantity may be updated in the future. Contact your sales rep. for the latest info.',
                    'image' => 'public_uploads_images_20240506_0f9527478ab30057741eebe91ded759a.jpg',
                ],
            ],
            'evomax_title' => 'EVOMAX Heating Core',
            'evomax_bg'    => 'public_uploads_images_20240417_1f5e31ac7567518c767e228436d2b848.jpg',
            'evomax_copy'  => 'Say goodbye to vape hardware that clogs, leaks, delivers unsatisfying flavors, and works well with distillates but poorly with high-terpene extracts such as live rosins and liquid diamonds!



Meet Justccell EVOMAX, the advanced heating platform that works flawlessly with your oil. Whether you are working with live rosin, liquid diamonds, live resin, distillate, or another type of oil, the EVOMAX ceramic heating core consistently delivers a clog-free, leak-free, and true-to-strain cannabis experience for your customers.',
            'details'      => [],
        ],
        'mini-tank' => [
            'name'     => 'Mini Tank',
            'category' => 'all-in-ones',
            'tagline'  => 'Ultra Compact All-In-One Vaporizer',
            'subtitle' => 'Ultra Compact All-In-One Vaporizer',
            'banner'   => 'public_uploads_images_20240507_80564d119e791271bb317cc91dd74828.png',
            'gallery'  =>             [
                'public_uploads_images_20240507_80564d119e791271bb317cc91dd74828.png',
            ],
            'spin'     => [],
            'specs'    =>             [
                'Tank volume: 0.5ml/1ml',
                'Battery capacity: 200mAh',
                'Dimensions: 63H x 36W x 15D (mm)/2.5H x 1.4W x 0.6D (in)',
                'Extremely compact and discreet body',
                'Aroma seal-off and anti-leakage switch (optional)',
                'SE heating element (standard) or EVOMAX heating element (optional)',
                'Clog-free dual air vents',
                'Clean vapor and enhanced safety via isolated airway',
                'Inhale activated',
                'USB-C charging',
                'Available for customization',
            ],
            'features' => [],
            'evomax_title' => 'EVOMAX Heating Element',
            'evomax_bg'    => 'public_uploads_images_20240417_1f5e31ac7567518c767e228436d2b848.jpg',
            'evomax_copy'  => 'Say goodbye to vape hardware that clogs, leaks, delivers unsatisfying flavors, and works well with distillates but poorly with high-terpene extracts such as live rosins and liquid diamonds!



Meet Justccell EVOMAX, the advanced heating platform that works flawlessly with your oil. Whether you are working with live rosin, liquid diamonds, live resin, distillate, or another type of oil, the EVOMAX ceramic heating element consistently delivers a clog-free, leak-free, and true-to-strain cannabis experience for your customers.',
            'details'      => [],
        ],
        'eco-star' => [
            'name'     => 'Eco Star',
            'category' => 'all-in-ones',
            'tagline'  => 'Sleek. Sustainable. All-Oil-Capable.',
            'subtitle' => 'Earth-Conscious All-In-One Vaporizer',
            'banner'   => 'public_uploads_images_20250207_effe61ef54aebd0e7fc85ebcc86ee2cd.png',
            'gallery'  =>             [
                'public_uploads_images_20250207_effe61ef54aebd0e7fc85ebcc86ee2cd.png',
            ],
            'spin'     => [],
            'specs'    =>             [
                'Tank volume: 0.5ml/1ml',
                'Battery capacity: 180mAh',
                'Dimensions: 89H x 22.1W x 16.6D (mm) / 3.5H x 0.87W x 0.65D (in)',
                'Compatible with distillates, live resins, live rosins, liquid diamonds, etc.',
                'Easily removable, recyclable battery',
                'Clog-free dual air vents',
                'Clean vapor via isolated airway',
                'LED indicator light',
                'Inhale activated',
                'USB-C charging',
                'Available for customization',
            ],
            'features' => [],
            'evomax_title' => 'EVOMAX Heating Core',
            'evomax_bg'    => 'public_uploads_images_20240417_1f5e31ac7567518c767e228436d2b848.jpg',
            'evomax_copy'  => 'Say goodbye to vape hardware that clogs, leaks, delivers unsatisfying flavors, and works well with distillates but poorly with high-terpene extracts such as live rosins and liquid diamonds!



Meet Justccell EVOMAX, the advanced heating platform that works flawlessly with your oil. Whether you are working with live rosin, liquid diamonds, live resin, distillate, or another type of oil, the EVOMAX ceramic heating core consistently delivers a clog-free, leak-free, and true-to-strain cannabis experience for your customers.',
            'details'      => [],
        ],
        'rosin-bar' => [
            'name'     => 'Rosin Bar',
            'category' => 'all-in-ones',
            'tagline'  => '100% Rosin-Ready',
            'subtitle' => '100% Rosin-Ready',
            'banner'   => 'public_uploads_images_20250102_5409e46e60179e2e1054c72da4423a8a.png',
            'gallery'  =>             [
                'public_uploads_images_20250102_5409e46e60179e2e1054c72da4423a8a.png',
            ],
            'spin'     => [],
            'specs'    =>             [
                'Tank Volume: 0.5ml',
                'Battery capacity: 280mAh',
                'Dimensions: 3.54H x 0.94W x 0.51D (in)/ 90H x 24W x 13D (mm)',
                'THC and terpene partitioned atomization',
                'Two clog-free/burnt flavor-free oil pathways',
                'Isolated airway for clean vapor and enhanced safety',
                'Full metal housing',
                'Inhale activated',
                'USB-C charging',
                'Food-grade mouthpiece and center post',
                'Available for customization',
            ],
            'features' => [],
            'evomax_title' => 'Isolated Airway, Cleaner Vapor',
            'evomax_bg'    => 'public_uploads_images_20240417_1f5e31ac7567518c767e228436d2b848.jpg',
            'evomax_copy'  => 'Unlike many conventional AIO devices, the airway within the Rosin Bar was designed to be isolated from the battery, PCBA, and other electronic components, ensuring the cleanest and safest possible vapor in every inhale.',
            'details'      => [],
        ],
        'voca-pro' => [
            'name'     => 'Voca Pro',
            'category' => 'all-in-ones',
            'tagline'  => 'Safety and Performance Perfected',
            'subtitle' => 'Clog-Free Dual Air-Vent All-In-One Device',
            'banner'   => 'public_uploads_images_20240812_61c733c4d0c3397a6faf5017f5a3a21b.png',
            'gallery'  =>             [
                'public_uploads_images_20240812_61c733c4d0c3397a6faf5017f5a3a21b.png',
            ],
            'spin'     => [],
            'specs'    =>             [
                'Tank Volume: 0.5ml/1ml',
                'Battery Capacity: 280mAh',
                'Dimensions: 76H x 36.1W x 13D (mm) / 2.99H x 1.42W x 0.51D (in)',
                'Preheat and child-resistant button',
                '0.5ml and 1ml options available at the same size',
                'Clog-free dual air vents',
                'Inhale activated',
                'USB-C charging',
                'Food-grade mouthpiece',
                'Medical-grade stainless steel center post',
                'Available for customization',
            ],
            'features' => [],
            'evomax_title' => 'Ceramic Heating Elements',
            'evomax_bg'    => 'public_uploads_images_20240417_1f5e31ac7567518c767e228436d2b848.jpg',
            'evomax_copy'  => 'Catering to the unique traits of various oils and viscosities, all of Justccell’s cartridges feature the renowned proprietary ceramic heating element. Justccell’s patented ceramic heating core was precisely engineered with the perfected porosity and structure that allows for purer flavors, more powerful potency, and minimal possibility of burnt tastes.',
            'details'      => [],
        ],
        'blanc' => [
            'name'     => 'Blanc',
            'category' => 'all-in-ones',
            'tagline'  => 'Full Ceramic All-In-One Device',
            'subtitle' => 'Full Ceramic All-In-One Device',
            'banner'   => 'public_uploads_images_20240116_a60dfad82bbff7ac268915d20bd4c163.png',
            'gallery'  =>             [
                'public_uploads_images_20240116_a60dfad82bbff7ac268915d20bd4c163.png',
            ],
            'spin'     => [],
            'specs'    =>             [
                'Tank Volume: 0.3ml/ 0.5ml/ 1ml',
                'Battery Capacity: 190mAh',
                'Dimensions: φ0.42 x 4.27/4.62/4.93 (in) / φ10.6 x 108.4/117.4/125.23 (mm)',
                'Snap-fit aluminum ceramic mouthpiece',
                'Zirconia ceramic center post',
                'Glass oil tank',
                'Metal body',
                'LED charging and inhalation indicator',
                'Inhale activated',
                'Micro-USB charging',
                'Available for customization',
            ],
            'features' => [],
            'evomax_title' => 'Ceramic Heating Elements',
            'evomax_bg'    => 'public_uploads_images_20240417_1f5e31ac7567518c767e228436d2b848.jpg',
            'evomax_copy'  => 'Catering to the unique traits of various oils and viscosities, all of Justccell’s cartridges feature the renowned proprietary ceramic heating element. Justccell’s patented ceramic heating core was precisely engineered with the perfected porosity and structure that allows for purer flavors, more powerful potency, and minimal possibility of burnt tastes.',
            'details'      => [],
        ],
        'slym' => [
            'name'     => 'Slym',
            'category' => 'all-in-ones',
            'tagline'  => 'Ultra-Thin. Ultra-Compact.',
            'subtitle' => 'Thinnest Yet to Date at 6.7mm',
            'banner'   => 'public_uploads_images_20230213_3933986251799de2a685e4063737e2cb.png',
            'gallery'  =>             [
                'public_uploads_images_20230213_3933986251799de2a685e4063737e2cb.png',
            ],
            'spin'     => [],
            'specs'    =>             [
                'Tank Volume: 0.3ml/0.5ml',
                'Battery Capacity: 280mAh/ 210mAh/ 280mAh/',
                '0.3ml & 0.5ml Dimensions：3.9H x 0.75W x 0.26D (in)/ 99H x 19W x 6.7D (mm)',
                'Justccell EVO heating core',
                'Ultra-slim lightweight design',
                'Full metal housing',
                'Medical-grade 316L stainless steel center post',
                'Inhale activation',
                'USB-C charging 0.5ml',
                'Available for customization',
            ],
            'features' => [],
            'evomax_title' => 'Ceramic Heating Elements',
            'evomax_bg'    => 'public_uploads_images_20240417_1f5e31ac7567518c767e228436d2b848.jpg',
            'evomax_copy'  => 'Catering to the unique traits of various oils and viscosities, all of Justccell’s cartridges feature the renowned proprietary ceramic heating element. Justccell’s patented ceramic heating core was precisely engineered with the perfected porosity and structure that allows for purer flavors, more powerful potency, and minimal possibility of burnt tastes.',
            'details'      => [],
        ],
        'ceramic-evomax' => [
            'name'     => 'Ceramic-EVOMAX',
            'category' => 'cartridge',
            'tagline'  => 'Full Ceramic Cart',
            'subtitle' => 'Full Ceramic Cart',
            'banner'   => 'public_uploads_images_20240724_08bd6433734bad9d99b5b9cbff5646fd.png',
            'gallery'  =>             [
                'public_uploads_images_20240724_08bd6433734bad9d99b5b9cbff5646fd.png',
            ],
            'spin'     => [],
            'specs'    =>             [
                'Tank volume: 0.5ml/1ml',
                'Dimensions: Φ0.43 x 2.12H/2.57H (in) / Φ11.0 x 53.9H/65.2H (mm)',
                'Resistance: 1.7Ω',
                'Aperture size: 4 x Φ2mm',
                'Snap-fit mouthpiece',
                'Borosilicate glass body',
                'Ceramic center post',
            ],
            'features' => [],
            'evomax_title' => '',
            'evomax_bg'    => 'public_uploads_images_20240417_1f5e31ac7567518c767e228436d2b848.jpg',
            'evomax_copy'  => '',
            'details'      => [],
        ],
        'th2-evomax' => [
            'name'     => 'TH2-EVOMAX',
            'category' => 'cartridge',
            'tagline'  => 'All-Oil-Capable Borosilicate Glass Cartridge',
            'subtitle' => 'All-Oil-Capable Borosilicate Glass Cartridge',
            'banner'   => 'public_uploads_images_20240418_5d48c79c07af862e9cfe7781f14bee14.png',
            'gallery'  =>             [
                'public_uploads_images_20240418_5d48c79c07af862e9cfe7781f14bee14.png',
            ],
            'spin'     => [],
            'specs'    =>             [
                'Tank volume: 0.5ml/1ml',
                'Dimensions: Φ0.41 x 2.04H/2.60H (in) / Φ10.5 x 51.8H/66.1H (mm)',
                'Resistance: 1.7Ω',
                'Aperture size: 4 x Φ2mm',
                'Snap-fit mouthpiece',
                'Borosilicate glass body',
                'Medical-grade stainless steel center post',
            ],
            'features' => [],
            'evomax_title' => '',
            'evomax_bg'    => 'public_uploads_images_20240417_1f5e31ac7567518c767e228436d2b848.jpg',
            'evomax_copy'  => '',
            'details'      => [],
        ],
        'm6t-evomax' => [
            'name'     => 'M6T-EVOMAX',
            'category' => 'cartridge',
            'tagline'  => 'All-Oil-Capable, BPA-Free Thermoplastic Cartridge',
            'subtitle' => 'All-Oil-Capable, BPA-Free Thermoplastic Cartridge',
            'banner'   => 'public_uploads_images_20240423_3cd1b054149dcdac21ea0842969824c2.png',
            'gallery'  =>             [
                'public_uploads_images_20240423_3cd1b054149dcdac21ea0842969824c2.png',
            ],
            'spin'     => [],
            'specs'    =>             [
                'Tank volume: 0.5ml/1ml',
                'Dimensions: Φ0.41 x 2.26H/2.67H (in) / Φ10.5 x 57.3H/67.8H (mm)',
                'Resistance: 1.7Ω',
                'Aperture size: 4 x Φ2mm',
                'Snap-fit mouthpiece',
                'BPA-free thermoplastic body',
                'Medical-grade stainless steel center post',
            ],
            'features' => [],
            'evomax_title' => '',
            'evomax_bg'    => 'public_uploads_images_20240417_1f5e31ac7567518c767e228436d2b848.jpg',
            'evomax_copy'  => '',
            'details'      => [],
        ],
        'th2-se' => [
            'name'     => 'TH2-SE',
            'category' => 'cartridge',
            'tagline'  => 'Borosilicate Glass Cartridge',
            'subtitle' => 'Borosilicate Glass Cartridge',
            'banner'   => 'public_uploads_images_20240522_3ab3d30d467a97f213945125b358b654.png',
            'gallery'  =>             [
                'public_uploads_images_20240522_3ab3d30d467a97f213945125b358b654.png',
            ],
            'spin'     => [],
            'specs'    =>             [
                'Standard 510 thread',
                'Tank Volume: 0.5ml/1ml/1.2ml',
                'Dimensions: Φ10.5 x 52/62/66 (mm) / Φ0.41 x 2.05/2.44/2.59 (in)',
                'Resistance: 1.4Ω',
                'Aperture size: 4 x Φ2mm',
                'Justccell ceramic heating element',
                'Snap-fit/screw-on mouthpiece (0.5ml & 1ml)',
                'Snap-fit mouthpiece (1.2ml)',
                'Borosilicate glass body',
                'Low-lead brass center post',
                'Available for customization',
            ],
            'features' => [],
            'evomax_title' => '',
            'evomax_bg'    => 'public_uploads_images_20240417_1f5e31ac7567518c767e228436d2b848.jpg',
            'evomax_copy'  => '',
            'details'      => [],
        ],
        'm6t-se' => [
            'name'     => 'M6T-SE',
            'category' => 'cartridge',
            'tagline'  => 'BPA-Free Thermoplastic Cartridge',
            'subtitle' => 'BPA-Free Thermoplastic Cartridge',
            'banner'   => 'public_uploads_images_20230630_efca403a99e32ee7c4526e6eb00a1595.png',
            'gallery'  =>             [
                'public_uploads_images_20230630_efca403a99e32ee7c4526e6eb00a1595.png',
            ],
            'spin'     => [],
            'specs'    =>             [
                'Tank Volume: 0.5ml/1ml',
                'Dimensions: Φ10.5 x 57.4/67.9 (mm) / Φ0.41 x 2.26/2.67 (in)',
                'Resistance: 1.4Ω',
                'Justccell ceramic heating element',
                'Snap-fit/press-in mouthpiece',
                'Low-lead brass center post',
                'BPA-free thermoplastic body',
                'Available for customization',
            ],
            'features' => [],
            'evomax_title' => '',
            'evomax_bg'    => 'public_uploads_images_20240417_1f5e31ac7567518c767e228436d2b848.jpg',
            'evomax_copy'  => '',
            'details'      => [],
        ],
        'luster-pro' => [
            'name'     => 'Luster Pro',
            'category' => 'pod-system',
            'tagline'  => 'Variable Wattage at Your Fingertips',
            'subtitle' => 'Sleek pod system with variable wattage',
            'banner'   => 'public_uploads_images_20240401_5330ba5336acfab3cdd25f260af2dcd2.png',
            'gallery'  =>             [
                'public_uploads_images_20240401_5330ba5336acfab3cdd25f260af2dcd2.png',
            ],
            'spin'     => [],
            'specs'    =>             [
                'Battery capacity: 350mAh',
                'Tank volume: 0.5ml/1ml',
                'Battery Dimensions: 3.58H x 0.83W x 0.43D (in)/91H x 21W x 11D (mm)',
                'Constant power output',
                '3 wattage settings (6.5/7.5/8.5W)',
                'Preheat and child-resistant button',
                'Full metal housing',
                'Drop-in magnetic connection',
                'Inhale activated',
                'USB-C charging',
                'Compatible with Luster Pods and Luster Pro Pods',
                'Available for customization',
            ],
            'features' => [],
            'evomax_title' => '',
            'evomax_bg'    => 'public_uploads_images_20240417_1f5e31ac7567518c767e228436d2b848.jpg',
            'evomax_copy'  => '',
            'details'      => [],
        ],
        'dart-x' => [
            'name'     => 'Dart-X',
            'category' => 'pod-system',
            'tagline'  => 'The Second Generation of Dart',
            'subtitle' => 'The Second Generation of Dart',
            'banner'   => 'public_uploads_images_20250305_d3c596b799f72238d81a78d16ee53966.png',
            'gallery'  =>             [
                'public_uploads_images_20250305_d3c596b799f72238d81a78d16ee53966.png',
            ],
            'spin'     => [],
            'specs'    =>             [
                'Battery Capacity: 480mAh',
                'Dimensions: 75.5H × 28.8W× 11.9D (mm)',
                'Full Metal Housing with Soft Touch Finish',
                '3 Unique Temperature Settings',
                'Constant Power Output',
                'Magnetic Connection',
                'Child-Resistant Lock',
                'Motion-Triggered LED Indicator',
                'Type-C Charging Enabled',
                'Available for Customization',
                'Compatible with DART (1st gen) Pods (0.5ml & 1.0ml)',
            ],
            'features' => [],
            'evomax_title' => '',
            'evomax_bg'    => 'public_uploads_images_20240417_1f5e31ac7567518c767e228436d2b848.jpg',
            'evomax_copy'  => '',
            'details'      => [],
        ],
        'dart' => [
            'name'     => 'Dart',
            'category' => 'pod-system',
            'tagline'  => 'Ultra Power at Your Fingertips.',
            'subtitle' => 'The First Pod System by Justccell.',
            'banner'   => 'public_uploads_images_20211018_bde1c43c00b90f8a4898e34fa0376bc1.png',
            'gallery'  =>             [
                'public_uploads_images_20211018_bde1c43c00b90f8a4898e34fa0376bc1.png',
            ],
            'spin'     => [],
            'specs'    =>             [
                'Battery Capacity: 480mAh',
                'Dimensions: 72.5H × 28.7W× 12.5D (mm)',
                'Comfortable Grip with Matte Finish',
                'Constant Power Output',
                'Inhale Activated',
                'Magnetic Connection',
                'Build-in LED Indicator',
                'Micro-USB Charging Enabled',
                'Available for Customization',
            ],
            'features' => [],
            'evomax_title' => '',
            'evomax_bg'    => 'public_uploads_images_20240417_1f5e31ac7567518c767e228436d2b848.jpg',
            'evomax_copy'  => '',
            'details'      => [],
        ],
        'bellos' => [
            'name'     => 'BELLOS',
            'category' => 'pod-system',
            'tagline'  => 'Feel the Moment',
            'subtitle' => 'Haptic Feedback',
            'banner'   => 'public_uploads_images_20211018_f63b7837d8d2557e1573f356e364adf0.png',
            'gallery'  =>             [
                'public_uploads_images_20211018_f63b7837d8d2557e1573f356e364adf0.png',
            ],
            'spin'     => [],
            'specs'    =>             [
                'Battery Capacity: 320mAh',
                'Dimensions: 67.6H × 30.0W × 12.6D (mm)',
                'Constant Power Output',
                'Haptic Feedback',
                'Magnetic Connection',
                'Build-in LED Indicator',
                'Micro-USB Charging Enabled',
                'Available for Customization',
            ],
            'features' => [],
            'evomax_title' => '',
            'evomax_bg'    => 'public_uploads_images_20240417_1f5e31ac7567518c767e228436d2b848.jpg',
            'evomax_copy'  => '',
            'details'      => [],
        ],
        'stylo' => [
            'name'     => 'Stylo',
            'category' => 'battery',
            'tagline'  => 'Precision at Your Fingertips',
            'subtitle' => 'Cool Clouds, Clear Control',
            'banner'   => 'public_uploads_images_20250407_8b49096ddef040e60e43f740198f0535.png',
            'gallery'  =>             [
                'public_uploads_images_20250407_8b49096ddef040e60e43f740198f0535.png',
            ],
            'spin'     => [],
            'specs'    =>             [
                'Battery capacity: 500mAh',
                'Dimensions: 57H x 42.4W x 20D (mm)/2.24H x 1.67W x 0.79D (in)',
                '15-second stable temp heating',
                'Digital display screen',
                '15-second preheat',
                '3 voltage settings (2.4V/2.8V/3.2V)',
                'Unobstructed oil view window',
                'Semi-transparent, compact body',
                'Compatible with 510 carts up to 14mm in diameter',
                'Inhale activated',
                'USB-C charging',
            ],
            'features' => [],
            'evomax_title' => '',
            'evomax_bg'    => 'public_uploads_images_20240417_1f5e31ac7567518c767e228436d2b848.jpg',
            'evomax_copy'  => '',
            'details'      => [],
        ],
        'palm-pro' => [
            'name'     => 'Palm Pro',
            'category' => 'battery',
            'tagline'  => 'Multi-Functional Palm-Fitting Battery',
            'subtitle' => 'Multi-Functional Palm-Fitting Battery',
            'banner'   => 'public_uploads_images_20231205_1544a0ee45c6725d20e885f965a4fb57.png',
            'gallery'  =>             [
                'public_uploads_images_20231205_1544a0ee45c6725d20e885f965a4fb57.png',
            ],
            'spin'     => [],
            'specs'    =>             [
                'Battery Capacity: 500mAh',
                'Dimensions: 2.26H x 1.65W x 0.53D (in) / 57.5H x 42W x 13.55D (mm)',
                'Standard 510 thread',
                '10-second preheat',
                '3 voltage settings (2.8/3.2/3.6V)',
                'Adjustable airflow',
                '3-bar battery status LED',
                'Drop-in magnetic connection',
                'Inhale activated',
                'Type-C charging',
                'Available for customization',
            ],
            'features' => [],
            'evomax_title' => '',
            'evomax_bg'    => 'public_uploads_images_20240417_1f5e31ac7567518c767e228436d2b848.jpg',
            'evomax_copy'  => '',
            'details'      => [],
        ],
        'go-stik' => [
            'name'     => 'Go Stik',
            'category' => 'battery',
            'tagline'  => 'Dual-Heat 510 Thread Battery',
            'subtitle' => 'Dual-Heat 510 Thread Battery',
            'banner'   => 'public_uploads_images_20230706_0c5f2f7fbc38369b8e5c4f72eb30b78a.png',
            'gallery'  =>             [
                'public_uploads_images_20230706_0c5f2f7fbc38369b8e5c4f72eb30b78a.png',
            ],
            'spin'     => [],
            'specs'    =>             [
                'Standard 510 thread',
                'Battery Capacity: 280mAh',
                'Dimensions: 91.5H x 20W x 15.2D (mm)/ 3.6H x 0.79W x 0.6D (in)',
                '2 temperature settings via slide switch (2.8/3.2V)',
                'Ergonomic, anti-slip body design',
                'Compatible with 510 cartridges of any size',
                'Inhale activated',
                'USB-C charging',
                'Available for customization',
            ],
            'features' => [],
            'evomax_title' => '',
            'evomax_bg'    => 'public_uploads_images_20240417_1f5e31ac7567518c767e228436d2b848.jpg',
            'evomax_copy'  => '',
            'details'      => [],
        ],
        'fino' => [
            'name'     => 'Fino',
            'category' => 'battery',
            'tagline'  => 'Endless Power, Variable Voltage, Serious Stealth',
            'subtitle' => '8 Variable Voltage Settings with Detachable Power Dock',
            'banner'   => 'public_uploads_images_20230817_6f917d3506895deda262311ba114014a.png',
            'gallery'  =>             [
                'public_uploads_images_20230817_6f917d3506895deda262311ba114014a.png',
            ],
            'spin'     => [],
            'specs'    =>             [
                'Battery capacity: 190mAh (Battery) + 1000mAh (Dock)',
                'Battery dimensions: 55.4H x 25W x 13.35D (mm) / 2.18H x 0.98W x 0.53D (in)',
                'Dock dimensions: 68.9H x 50.6W x 20D (mm) / 2.71H x 1.99W x 0.78D (in)',
                'Detachable Power Dock',
                'Discreet Mini Battery with oil view window',
                '8 voltage settings (0.2V increments between 2.2V-3.6V)',
                '10-second preheat',
                'Drop-in magnetic connection compatible with 510 carts',
                'Highly intuitive LED indicator lights',
                'Inhale activated',
                'USB-C charging',
                'Available for customization',
            ],
            'features' => [],
            'evomax_title' => '',
            'evomax_bg'    => 'public_uploads_images_20240417_1f5e31ac7567518c767e228436d2b848.jpg',
            'evomax_copy'  => '',
            'details'      => [],
        ],
        'sandwave' => [
            'name'     => 'Sandwave',
            'category' => 'battery',
            'tagline'  => 'Style Meets Power',
            'subtitle' => 'Variable Voltage 510 Thread Battery',
            'banner'   => 'public_uploads_images_20230811_097aa8efa3e032454546c9cc20e18992.png',
            'gallery'  =>             [
                'public_uploads_images_20230811_097aa8efa3e032454546c9cc20e18992.png',
                'public_uploads_images_20230706_0c5f2f7fbc38369b8e5c4f72eb30b78a.png',
            ],
            'spin'     => [],
            'specs'    =>             [
                'Battery Capacity: 400mAh',
                'Dimensions: 60H x 38.2W x 16.2D (mm)/ 2.36H x 1.5W x 0.64D (in)',
                '3 temperature settings via slide switch (2.8/3.2/3.6V)',
                'Drop-in magnetic connection compatible with 510 thread cartridges',
                'Inhale activated',
                'USB-C charging',
                'Available for customization',
            ],
            'features' => [],
            'evomax_title' => '',
            'evomax_bg'    => 'public_uploads_images_20240417_1f5e31ac7567518c767e228436d2b848.jpg',
            'evomax_copy'  => '',
            'details'      => [],
        ],
        'm3b-plus' => [
            'name'     => 'M3B Plus',
            'category' => 'battery',
            'tagline'  => 'Cartridge Compatibility Maximized',
            'subtitle' => 'Cart Size-Flexible Design with 3 Voltage Settings',
            'banner'   => 'public_uploads_images_20240227_89397ff3de880aca770571a81e29c4d2.png',
            'gallery'  =>             [
                'public_uploads_images_20240227_89397ff3de880aca770571a81e29c4d2.png',
            ],
            'spin'     => [],
            'specs'    =>             [
                'Battery capacity: 550mAh',
                'Dimensions: φ0.55 x 3.48 (in) / φ14 x 88.3H (mm)',
                '3 voltage settings (2.8/3.2/3.6V)',
                '10-second preheat',
                'Child-resistant lock',
                'Full metal housing',
                'LED indicator lights',
                'Compatible with 510 cartridges of any size',
                'Standard 510 thread',
                'Button activated',
                'USB-C charging',
                'Available for customization',
            ],
            'features' => [],
            'evomax_title' => '',
            'evomax_bg'    => 'public_uploads_images_20240417_1f5e31ac7567518c767e228436d2b848.jpg',
            'evomax_copy'  => '',
            'details'      => [],
        ],
    ];
}
